"""src/reliability/schema.py
Data structures and enums for Phase 9 Reliability and Failure-Safety layer.
"""

from dataclasses import dataclass, asdict
from enum import Enum
import math
from typing import Dict, Any, List, Optional


class ReliabilityAction(str, Enum):
    """Reliability decision action states."""
    ACCEPT = "ACCEPT"
    ACCEPT_WITH_WARNING = "ACCEPT_WITH_WARNING"
    ESCALATE = "ESCALATE"
    ABSTAIN = "ABSTAIN"


class FailureMode(str, Enum):
    """Structured 8-class failure taxonomy."""
    F01_RETRIEVAL_FAILURE = "F01_RETRIEVAL_FAILURE"
    F02_VISUAL_DEGRADATION = "F02_VISUAL_DEGRADATION"
    F03_INSUFFICIENT_EVIDENCE = "F03_INSUFFICIENT_EVIDENCE"
    F04_NUMERIC_CONFLICT = "F04_NUMERIC_CONFLICT"
    F05_TABLE_ALIGNMENT_FAILURE = "F05_TABLE_ALIGNMENT_FAILURE"
    F06_SPATIAL_GROUNDING_FAILURE = "F06_SPATIAL_GROUNDING_FAILURE"
    F07_CROSS_PAGE_CONFLICT = "F07_CROSS_PAGE_CONFLICT"
    F08_MODEL_DISAGREEMENT = "F08_MODEL_DISAGREEMENT"


@dataclass
class UncertaintyVector:
    """8-Dimensional Observable Uncertainty Vector U in [0, 1]^8."""
    u_retrieval: float
    u_semantic: float
    u_spatial: float
    u_numeric: float
    u_table: float
    u_sufficiency: float
    u_quality: float
    u_agreement: float

    def __post_init__(self):
        # Clip all values to [0.0, 1.0]
        self.u_retrieval = max(0.0, min(1.0, float(self.u_retrieval)))
        self.u_semantic = max(0.0, min(1.0, float(self.u_semantic)))
        self.u_spatial = max(0.0, min(1.0, float(self.u_spatial)))
        self.u_numeric = max(0.0, min(1.0, float(self.u_numeric)))
        self.u_table = max(0.0, min(1.0, float(self.u_table)))
        self.u_sufficiency = max(0.0, min(1.0, float(self.u_sufficiency)))
        self.u_quality = max(0.0, min(1.0, float(self.u_quality)))
        self.u_agreement = max(0.0, min(1.0, float(self.u_agreement)))

    def to_array(self) -> List[float]:
        return [
            self.u_retrieval,
            self.u_semantic,
            self.u_spatial,
            self.u_numeric,
            self.u_table,
            self.u_sufficiency,
            self.u_quality,
            self.u_agreement,
        ]

    @property
    def l2_norm(self) -> float:
        """Normalized L2 norm in [0, 1]."""
        arr = self.to_array()
        sq_sum = sum(x * x for x in arr)
        # Max possible L2 norm of 8 elements with value 1.0 is sqrt(8)
        return min(1.0, math.sqrt(sq_sum) / math.sqrt(8.0))

    @property
    def mean(self) -> float:
        arr = self.to_array()
        return sum(arr) / len(arr)

    @classmethod
    def zeros(cls) -> "UncertaintyVector":
        return cls(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)

    @classmethod
    def ones(cls) -> "UncertaintyVector":
        return cls(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0)


@dataclass
class ReliabilityDecision:
    """Decision output generated by abstention policy."""
    action: ReliabilityAction
    confidence: float
    uncertainty_norm: float
    operating_point: str
    reason: str
    warning_flag: Optional[str] = None


@dataclass
class FailureModeResult:
    """Diagnosed failure mode result."""
    primary_failure: Optional[FailureMode]
    secondary_failure: Optional[FailureMode]
    confidence_deficit: float
    diagnostics: Dict[str, Any]


@dataclass
class ReliabilityPackage:
    """Full bundle returned by the reliability pipeline."""
    doc_id: str
    query_id: str
    decision: ReliabilityDecision
    uncertainty_vector: UncertaintyVector
    raw_confidence: float
    calibrated_confidence: float
    failure_mode: Optional[FailureModeResult] = None
    metadata: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["decision"]["action"] = self.decision.action.value
        if self.failure_mode and self.failure_mode.primary_failure:
            d["failure_mode"]["primary_failure"] = self.failure_mode.primary_failure.value
        if self.failure_mode and self.failure_mode.secondary_failure:
            d["failure_mode"]["secondary_failure"] = self.failure_mode.secondary_failure.value
        return d
